<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class suscripcion_has_destino_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get suscripcion_has_destino by id_suscripcion_has_destino
     */
    function get_suscripcion_has_destino($id_suscripcion_has_destino)
    {
        return $this->db->get_where('suscripcion_has_destino',array('id_suscripcion_has_destino'=>$id_suscripcion_has_destino))->row_array();
    }
    
    /*
     * Get all suscripcion_has_destinos count
     */
    function get_all_suscripcion_has_destinoes_count()
    {
        $this->db->from('suscripcion_has_destino');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all suscripcion_has_destinos
     */
    function get_all_suscripcion_has_destinoes($params = array())
    {
        $this->db->order_by('id_suscripcion_has_destino', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('suscripcion_has_destino')->result_array();
    }
        
    /*
     * function to add new suscripcion_has_destino
     */
    function add_suscripcion_has_destino($params)
    {
        $this->db->insert('suscripcion_has_destino',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update suscripcion_has_destino
     */
    function update_suscripcion_has_destino($id_suscripcion_has_destino,$params)
    {
        $this->db->where('id_suscripcion_has_destino',$id_suscripcion_has_destino);
        return $this->db->update('suscripcion_has_destino',$params);
    }
    
    /*
     * function to delete suscripcion_has_destino
     */
    function delete_suscripcion_has_destino($id_suscripcion_has_destino)
    {
        return $this->db->delete('suscripcion_has_destino',array('id_suscripcion_has_destino'=>$id_suscripcion_has_destino));
    }
}
