<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class suscripcion_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get suscripcion by id_suscripcion
     */
    function get_suscripcion($id_suscripcion)
    {
        return $this->db->get_where('suscripcion',array('id_suscripcion'=>$id_suscripcion))->row_array();
    }
    /*
     * Get suscripcion by email
     */
    function get_state_suscripcion($email)
    {
        return $this->db->get_where('suscripcion',array('email_suscripcion'=>strtolower($email)))->row_array();
    }
    /*
     * Get all suscripcions count
     */
    function get_all_suscripciones_count()
    {
        $this->db->from('suscripcion');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all suscripcions
     */
    function get_all_suscripciones($params = array())
    {
        $this->db->order_by('id_suscripcion', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('suscripcion')->result_array();
    }
        
    /*
     * function to add new suscripcion
     */
    function add_suscripcion($params)
    {
        $this->db->insert('suscripcion',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update suscripcion
     */
    function update_suscripcion($id_suscripcion,$params)
    {
        $this->db->where('id_suscripcion',$id_suscripcion);
        return $this->db->update('suscripcion',$params);
    }
    
    /*
     * function to delete suscripcion
     */
    function delete_suscripcion($id_suscripcion)
    {
        return $this->db->delete('suscripcion',array('id_suscripcion'=>$id_suscripcion));
    }
}
